### ISSUE TITLE
RMW processing of read after write

### ISSUE THREAD

**Issue by alannair** [TheNetAdmin/VANS#1]
Consider the situation when a read request is popped from LSQ to be processed. Suppose in RMW buffer there is a already an entry corresponding to a write request (write_rmw for example).  Being a write request, the entry will have an empty queue as *pending_request_cl_index*. 
But in **rmw.cc** in `tick_lsq_read`:

    if (entry.pending_request_cl_index.empty()) {
                    throw std::runtime_error(
                        "Internal error, "
                        "the read request to patch does not have any pending read request, maybe a code bug.");
                }

Is this okay, to throw an error in the aforementioned circumstance, which itself is not erroneous?
Would not a better idea in this case (i.e. a read request encountering a pending write) be to just wait till it *valid_to_read* becomes `true` after which the read can be fast-forwarded?

**Comment by TheNetAdmin** [comment]
Hi, thank you for pointing out this situation. This seems to be a bug introduced during the code refactoring before the code release.

I will fix it in the upcoming commits these days.

**Comment by TheNetAdmin** [comment]
Hi, I just updated the code, now it also checks if the current pending request is a read request.

Please try the new code and see if there's any remaining bug.

**Comment by alannair** [comment]
The code seems fine now. Thanks.
