### ISSUE TITLE
Read Requests to Multiple Cachelines in a Single RMW Entry

### ISSUE THREAD

**Issue by alannair** [TheNetAdmin/VANS#2]
Suppose the RMW buffer contains a *read_ff* entry with a *pending_request_cl_index* queue of two or more elements (This is possible - suppose a *read_ff* entry gets added to the RMW buffer. It will have a *pending_request_cl_index* with one element. Then, another read request to another cacheline in the same block is encountered, and it gets added to the previously mentioned entry).

When the entry reaches the *pending_readout* state, first `issue_roq` is called which pops one element from *pending_request_cl_index*. Then the following transition (**rmw.cc**: `init_state_trans_table(): trans(read_ff, pending_readout)` ) occurs:

    if (!entry.pending_request_cl_index.empty()) {
          /* Go to pending_read state if there are pending requests. */
          entry.state = request_state::pending_read;
      } else {
          entry.state   = request_state::end;
          entry.pending = false;
      }

Note that there is no transition defined for `(read_ff, pending_read)`, making it an invalid state. So, this code throws up an error if a *read_ff* request is encountered with more than one element in *pending_request_cl_index*.

One suggestion would be that the above code may be edited as follows:

    if (!entry.pending_request_cl_index.empty()) {
            /* Go to pending_read state if there are pending requests. */
            entry.state = request_state::pending_readout; // edited
        } else {
            entry.state   = request_state::end;
            entry.pending = false;
        }

Now, the entry stays in the same *pending_readout* state as long as the elements in *pending_request_cl_index queue* get popped one by one, and it exits the state only when all elements in the *pending_request_cl_index* queue have been popped.

**Comment by alannair** [comment]
Oh, I'm sorry. I'm using an old commit of the repository.

**Comment by alannair** [comment]
Delete this issue. Apologies :)

**Comment by TheNetAdmin** [comment]
Yes I just fixed that bug yesterday:smiley:
