### ISSUE TITLE
undefined reference errors during make

### ISSUE THREAD

**Issue by GrayXu** [TheNetAdmin/VANS#3]
Hi, I tried to build _VANS_, but encountered some errors...  

enviroments:  
Ubunutu 18  
Linux 5.4.0-62-generic  
cmake version 3.10.2  
gcc version 8.2.0 (GCC)

```
git clone ..
cmake ..
make -j
```
then get ouputs below
```
CMakeFiles/vans.dir/src/general/factory.cpp.o: In function `vans::dumper::dumper(vans::dumper::type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
factory.cpp:(.text._ZN4vans6dumperC2ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4vans6dumperC5ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1a6): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
factory.cpp:(.text._ZN4vans6dumperC2ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4vans6dumperC5ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1b5): undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
factory.cpp:(.text._ZN4vans6dumperC2ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4vans6dumperC5ENS0_4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1bf): undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/vans.dir/build.make:250: recipe for target '../bin/vans' failed
make[2]: *** [../bin/vans] Error 1
CMakeFiles/Makefile2:611: recipe for target 'CMakeFiles/vans.dir/all' failed
make[1]: *** [CMakeFiles/vans.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

thx!

**Comment by TheNetAdmin** [comment]
Seems the `filesystem` feature is not supported well on your platform. Can you try comment the lines creating a new directory and recompile?

**Comment by LittleSaltFish** [comment]
Same Error occur when making files：
![image](https://user-images.githubusercontent.com/45428395/105952303-5b757d80-60ac-11eb-8150-527f5a608213.png)
And the error still exists when recompile.

Env:
Debian GNU/Linux 10 (buster)
cmake version 3.13.4
gcc (Debian 8.3.0-6) 8.3.0

**Comment by TheNetAdmin** [comment]
I just tried the GCC 8.3.0 and can reproduce this error.

Seems the GCC 8 does not support `filesystem` very well. The GCC 9 should do the job, and I used GCC 10 for development.

I'll post a fix to replace the `filesystem`.

**Comment by TheNetAdmin** [comment]
I just replaced the `filesystem` calls with `mkdir`. Please try the new code.

Feel free to reopen this issue if the problem still exists.

**Comment by GrayXu** [comment]
Thanks! The new codes work.
