### ISSUE TITLE
Is there a problem with the AIT module obtaining data from the DRAM?

### ISSUE THREAD

**Issue by Distancess** [TheNetAdmin/VANS#4]
https://github.com/TheNetAdmin/VANS/blob/2c78b7bb2b0349739f49958b748af0384efb0b95/src/general/ait.cpp#L512
The granularity of the lmemq request is 256 bytes. When the request in this queue obtains data from the DRAM, four 64 bytes should be sent to the DRAM. In the code, the value of `lmemq_state.subreq_cnt` is 1. Therefore, only one 64B request is sent to the DRAM and the actual 256B data is obtained. Am I wrong? Or is there a problem with the code?

**Comment by TheNetAdmin** [comment]
Yes it should be 4, this is a bug introduced while preparing the open source version.

**Comment by TheNetAdmin** [comment]
Just pushed the update, this update may affect the latency accuracy and thus you may want to double check and tune the timings defined in the configuration file.
