### ISSUE TITLE
does this simulator can support the semantics of Px86?

### ISSUE THREAD

**Issue by ZimaBlue307** [TheNetAdmin/VANS#8]
Hi, I am just a fresh learner of this field, I want know does this simulator can support the semantics of [Px86](https://dl.acm.org/doi/pdf/10.1145/3371079)? Thank you very much for the reply.

**Comment by TheNetAdmin** [comment]
VANS is a cycle-level memory simulator that only takes care of the load and store events. You may need to use VANS with other processor simulators or trace-based simulators for your use case.

**Comment by ZimaBlue307** [comment]
the tace file only cantains the address and read/write. What about the value it writes to the address or the value it reads from the address?

**Comment by TheNetAdmin** [comment]
The value is taken care of by gem5, or if you don't use gem5, then you need to implement that feature. I remember at some point I implemented this feature but then removed it as gem5 takes care of it
